# Version of the SSM Automation document schema
schemaVersion: "0.3"

# Description block explains the purpose and input/output of the document
description: |
  ### Document Name - AWSConfigRemediation-EnforceEC2InstanceIMDSv2

  ## What does this document do?
  This document enforces that Amazon EC2 instances use Instance Metadata Service Version 2 (IMDSv2) by modifying the instance metadata settings using the ModifyInstanceMetadataOptions API.

  ## Input Parameters
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
  * InstanceId: (Required) The ID of the Amazon EC2 instance.

  ## Output Parameters
  * ModifyInstanceMetadataOptions.Output: The standard HTTP response from the ModifyInstanceMetadataOptions API.

# IAM role used to run the automation
assumeRole: "{{ AutomationAssumeRole }}"

# Define input parameters for the automation document
parameters:
  AutomationAssumeRole:
    type: String
    description: (Required) ARN of the IAM role for automation
    allowedPattern: ^arn:aws[a-z0-9-]*:iam::\d{12}:role/[\w-/.@+=,]{1,1017}$
  InstanceId:
    type: String
    description: EC2 instance ID to apply the change to
    allowedPattern: ^i-[a-z0-9]{17}$|^i-[a-z0-9]{8}$

# Output values returned by the document
outputs:
  - ModifyInstanceMetadataOptions.Output

# Main steps executed during automation
mainSteps:
  # Step to modify the instance metadata settings
  - name: ModifyInstanceMetadataOptions
    action: "aws:executeAwsApi"
    description: |
      ## ModifyInstanceMetadataOptions
      Modifies the instance metadata settings to enforce IMDSv2.
      ## Outputs
      * Output: Standard response from API.
    timeoutSeconds: 600
    isEnd: false
    inputs:
      Service: ec2
      Api: ModifyInstanceMetadataOptions
      InstanceId: "{{ InstanceId }}"
      HttpTokens: "required"
    outputs:
      - Name: Output
        Selector: $
        Type: StringMap

  # Step to verify that the metadata setting has been applied
  - name: VerifyEC2IMDSv2Enforced
    action: "aws:assertAwsResourceProperty"
    timeoutSeconds: 600
    isEnd: true
    description: |
      ## DescribeInstances
      Verifies IMDSv2 is now enforced on the instance.
    inputs:
      Service: ec2
      Api: DescribeInstances
      InstanceIds:
        - "{{ InstanceId }}"
      PropertySelector: $.Reservations[0].Instances[0].MetadataOptions.HttpTokens
      DesiredValues:
        - required
